[all:vars]
ansible_ssh_user=allianz
ansible_ssh_private_key_file=./private_key.pem

[trainer]
trainer-master ansible_host=35.128.81.204
trainer-worker1 ansible_host=34.101.160.185
trainer-worker2 ansible_host=34.101.32.107

[trainee1]
trainee1-master ansible_host=34.50.78.97
trainee1-worker1 ansible_host=34.101.123.9
trainee1-worker2 ansible_host=34.128.108.153

[trainee2]
trainee2-master ansible_host=35.50.90.81
trainee2-worker1 ansible_host=34.128.125.154
trainee2-worker2 ansible_host=34.128.79.72

[trainee4]
trainee4-master ansible_host=35.128.118.170
trainee4-worker1 ansible_host=34.128.98.37
trainee4-worker2 ansible_host=34.50.77.128

[trainee5]
trainee5-master ansible_host=35.128.99.136
trainee5-worker1 ansible_host=34.101.232.252
trainee5-worker2 ansible_host=34.101.57.111

[trainee6]
trainee6-master ansible_host=35.101.224.33
trainee6-worker1 ansible_host=34.50.90.41
trainee6-worker2 ansible_host=34.101.43.116

[trainee7]
trainee7-master ansible_host=35.101.88.232
trainee7-worker1 ansible_host=34.50.83.108
trainee7-worker2 ansible_host=34.128.124.42

[trainee8]
trainee8-master ansible_host=35.128.84.110
trainee8-worker1 ansible_host=34.101.168.90
trainee8-worker2 ansible_host=34.101.172.182

[trainee9]
trainee9-master ansible_host=35.50.78.248
trainee9-worker1 ansible_host=34.50.66.127
trainee9-worker2 ansible_host=34.101.254.75

[trainee09]
trainee09-master ansible_host=35.128.82.168
trainee09-worker1 ansible_host=34.101.244.64
trainee09-worker2 ansible_host=34.101.231.73

[trainee10]
trainee10-master ansible_host=34.128.85.200
trainee10-worker1 ansible_host=34.101.160.233
trainee10-worker2 ansible_host=34.101.152.136

[trainee11]
trainee11-master ansible_host=34.101.91.229
trainee11-worker1 ansible_host=34.101.155.58
trainee11-worker2 ansible_host=34.50.70.95

[trainee12]
trainee12-master ansible_host=34.128.97.125
trainee12-worker1 ansible_host=34.101.103.32
trainee12-worker2 ansible_host=34.101.109.176
